version: '3.0'

services:
  notary:
    image: corda/community:4.9.1-zulu-openjdk8
    container_name: notary
    user: root
    ports:
      - "10003:10003"
    volumes:
      - ./notary/node.conf:/etc/corda/node.conf:rw
      - ./notary/certificates:/opt/corda/certificates:rw
      - ./notary/persistence:/opt/corda/persistence:rw
      - ./notary/logs:/opt/corda/logs:rw
      - ./shared/cordapps:/opt/corda/cordapps:rw
      - ./shared/drivers:/opt/corda/drivers:rw
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos:rw
      - ./shared/network-parameters:/opt/corda/network-parameters:rw
    command: sh -c "java -jar /opt/corda/bin/corda.jar run-migration-scripts --core-schemas --app-schemas --base-directory=/opt/corda --config-file=/etc/corda/node.conf; java -jar /opt/corda/bin/corda.jar --config-file=/etc/corda/node.conf"

  partya:
    image: corda/community:4.9.1-zulu-openjdk8
    container_name: partya
    user: root
    ports:
      - "10004:10003"
    volumes:
      - ./partya/node.conf:/etc/corda/node.conf
      - ./partya/certificates:/opt/corda/certificates
      - ./partya/persistence:/opt/corda/persistence:rw
      - ./partya/logs:/opt/corda/logs:rw
      - ./shared/drivers:/opt/corda/drivers
      - ./shared/cordapps:/opt/corda/cordapps:rw
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters
    command: sh -c "java -jar /opt/corda/bin/corda.jar run-migration-scripts --core-schemas --app-schemas --base-directory=/opt/corda --config-file=/etc/corda/node.conf; java -jar /opt/corda/bin/corda.jar --config-file=/etc/corda/node.conf"

  partyb:
    image: corda/community:4.9.1-zulu-openjdk8
    container_name: partyb
    user: root
    ports:
      - "10005:10003"
    volumes:
      - ./partyb/node.conf:/etc/corda/node.conf
      - ./partyb/certificates:/opt/corda/certificates
      - ./partyb/persistence:/opt/corda/persistence:rw
      - ./partyb/logs:/opt/corda/logs:rw
      - ./shared/drivers:/opt/corda/drivers
      - ./shared/cordapps:/opt/corda/cordapps:rw
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters
    command: sh -c "java -jar /opt/corda/bin/corda.jar run-migration-scripts --core-schemas --app-schemas --base-directory=/opt/corda --config-file=/etc/corda/node.conf; java -jar /opt/corda/bin/corda.jar --config-file=/etc/corda/node.conf"
  
  partyc:
    image: corda/community:4.9.1-zulu-openjdk8
    container_name: partyc
    user: root
    ports:
      - "10006:10003"
    volumes:
      - ./partyc/node.conf:/etc/corda/node.conf
      - ./partyc/certificates:/opt/corda/certificates
      - ./partyc/persistence:/opt/corda/persistence:rw
      - ./partyc/logs:/opt/corda/logs:rw
      - ./shared/drivers:/opt/corda/drivers
      - ./shared/cordapps:/opt/corda/cordapps:rw
      - ./shared/additional-node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters
    command: sh -c "java -jar /opt/corda/bin/corda.jar run-migration-scripts --core-schemas --app-schemas --base-directory=/opt/corda --config-file=/etc/corda/node.conf; java -jar /opt/corda/bin/corda.jar --config-file=/etc/corda/node.conf"
